.PHONY: mainA-1

mainA-1:
	g++ -std=c++11 -o mainA-1.out Node.cpp LinkedList.cpp mainA-1.cpp
	./mainA-1.out

BigNumCalc_main:
	g++ -std=c++11 -o BigNumCalc_main.out BigNumCalc.cpp BigNumCalc_main.cpp
	./BigNumCalc_main.out
